---
'on':
  push:
    paths:
      - .github/workflows/main.yaml
      - dist/main.js

jobs:
  main:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
          - self-hosted
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Run colpal/setup-yq@${{ github.ref }}
        uses: ./
        with:
          yq-version: 4.6.1

      - run: yq --version
