---
'on':
  push:
    paths:
      - .github/workflows/main.yaml
      - dist/main.js

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        exclude:
          - yq-version: "0.1"
            os: macos-13
          - yq-version: "0.1"
            os: macos-14
          - yq-version: "0.1"
            os: macos-15
          - yq-version: "1.15.0"
            os: macos-13
          - yq-version: "1.15.0"
            os: macos-14
          - yq-version: "1.15.0"
            os: macos-15
          - yq-version: "2.4.1"
            os: macos-14
          - yq-version: "2.4.1"
            os: macos-15
          - yq-version: "3.4.1"
            os: macos-14
          - yq-version: "3.4.1"
            os: macos-15
        yq-version:
          - 4.44.6
          - 3.4.1
          - 2.4.1
          - 1.15.0
          - "0.1"
        os:
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-20.04
          - windows-2025
          - windows-2022
          - windows-2019
          - macos-13
          - macos-14
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Run colpal/setup-yq@${{ github.ref }}
        uses: ./
        with:
          yq-version: ${{ matrix.yq-version }}

      - run: yq --version

      - if: matrix.yq-version != '0.1'
        run: yq --version | grep -qF "$YQ_VERSION"
        env:
          YQ_VERSION: ${{ matrix.yq-version }}
