---
'on':
  push:
    paths:
      - .github/workflows/main.yaml
      - dist/main.js

jobs:
  main:
    strategy:
      matrix:
        exclude:
          - os: macos-latest
            yq-version: "0.1"
        yq-version:
          - 4.30.6
          - 3.4.1
          - 2.4.1
          - 1.15.0
          - "0.1"
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Run colpal/setup-yq@${{ github.ref }}
        uses: ./
        with:
          yq-version: ${{ matrix.yq-version }}

      - run: yq --version
