---
'on':
  push:
    paths:
      - .github/workflows/main.yaml
      - dist/main.js

jobs:
  main:
    strategy:
      matrix:
        yq-version:
          - 4.30.6
          - 3.4.1
          - 2.4.1
          - 1.15.0
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Run colpal/setup-yq@${{ github.ref }}
        uses: ./
        with:
          yq-version: ${{ matrix.yq-version }}

      - run: yq --version | grep -qF "$YQ_VERSION"
        env:
          YQ_VERSION: ${{ matrix.yq-version }}
